/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/layout/Button.vue')['default']
    Expan: typeof import('./src/components/Expan.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayoutOne: typeof import('./src/components/layout/LayoutOne.vue')['default']
    LayoutThree: typeof import('./src/components/layout/LayoutThree.vue')['default']
    LayoutTwo: typeof import('./src/components/layout/LayoutTwo.vue')['default']
    Nav1: typeof import('./src/components/nav/Nav1.vue')['default']
    Nav2: typeof import('./src/components/nav/Nav2.vue')['default']
    Nav3: typeof import('./src/components/nav/Nav3.vue')['default']
    Nav4: typeof import('./src/components/nav/Nav4.vue')['default']
  }
}
